### ISSUE TITLE
Issue: The placeholder text for the Sign In page's "Email Address" field is misspelled

### ISSUE THREAD

**Issue by Preciouschukwuemeka** [treehouse-apprenticeship/athena_irv3#3]
Issue Description
On the Sign In page, the placeholder text for the "Email Address" field is misspelled as "Email Addrss".

Steps to Reproduce

Using the React client, click on the "Sign In" link displayed in the header to browse to the "Sign In" page.
Notice that the placeholder text for the "Email Address" field is misspelled as "Email Addrss".isspelled as "Email Addrss".

**Comment by Jenpar1674** [comment]
Fixed typo. Pushed.
