### ISSUE TITLE
Issue: The "Materials Needed" section doesn't display on the Course Detail Page 

### ISSUE THREAD

**Issue by mignonne87** [treehouse-apprenticeship/athena_irv3#6]
When viewing the Build a Basic Bookcase course, the "Materials Needed" section doesn't display. Using the React client, browse to the "Build a Basic Bookcase" course's Course Detail page. 
You can use the React Developer Tools to confirm that the Course Detail React component state contains an object whose materials Needed property is set to a non-null, non-empty value.

**Comment by hallmlu** [comment]
Updated code to show materialsNeeded
