### ISSUE TITLE
Attempting to update a course produces an error

### ISSUE THREAD

**Issue by mignonne87** [treehouse-apprenticeship/athena_irv3#7]
Attempting to update a course results in the "Error" page being displayed.
Using the React client, click on the "Sign In" link displayed in the header to browse to the "Sign In" page.  Using Joe's user information email address: joe@smith.com password: joepassword
Browse to the course Detail page for the "Build a Basic Bookcase" course. Click the Update Course button at the top of the browse to the Update Course Page. Click the Update Course button at the bottom of the page to update the course. The error page displays instead of the expected Course Detail page.

**Comment by hallmlu** [comment]
Change the GET request on line 110 f the data.js file in the client side to a PUT request.
